FROM node:20-alpine AS builder

WORKDIR /app

COPY backend/package.json backend/yarn.lock* ./
RUN yarn install --frozen-lockfile

COPY backend/ .
RUN yarn prisma generate
RUN yarn build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

EXPOSE 4000

CMD ["node", "dist/server.js"]
